/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class piApproximationMethods_CodeInC */

#ifndef _Included_piApproximationMethods_CodeInC
#define _Included_piApproximationMethods_CodeInC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     piApproximationMethods_CodeInC
 * Method:    madhavaLeibniz
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_piApproximationMethods_CodeInC_madhavaLeibniz
  (JNIEnv *, jobject, jlong);

/*
 * Class:     piApproximationMethods_CodeInC
 * Method:    madhavaLeibnizPrintCalc
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_piApproximationMethods_CodeInC_madhavaLeibnizPrintCalc
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
